(function(){'use strict';
const META={en:['English','🇬🇧','ltr'],ar:['العربية','🇸🇦','rtl'],fa:['فارسی','🇮🇷','rtl'],de:['Deutsch','🇩🇪','ltr'],nl:['Nederlands','🇳🇱','ltr'],ru:['Русский','🇷🇺','ltr'],pt:['Português','🇵🇹','ltr'],fr:['Français','🇫🇷','ltr'],zh:['中文','🇨🇳','ltr'],ja:['日本語','🇯🇵','ltr'],az:['Azərbaycanca','🇦🇿','ltr'],tr:['Türkçe','🇹🇷','ltr'],ur:['اردو','🇵🇰','rtl'],pl:['Polski','🇵🇱','ltr'],it:['Italiano','🇮🇹','ltr'],id:['Bahasa Indonesia','🇮🇩','ltr'],ko:['한국어','🇰🇷','ltr'],uk:['Українська','🇺🇦','ltr'],ro:['Română','🇷🇴','ltr'],ms:['Bahasa Melayu','🇲🇾','ltr'],es:['Español','🇪🇸','ltr']};
const RTL=new Set(['ar','fa','ur']),CACHE={},LOAD={}; const KEY='odyssey_lang';
const scriptEl=document.currentScript; const BASE=(scriptEl&&scriptEl.src?scriptEl.src.replace(/[^/]*$/,''):'js/')+'../i18n/';
function lang(){const x=localStorage.getItem(KEY);return META[x]?x:'en'}
function load(code){code=META[code]?code:'en'; if(CACHE[code])return Promise.resolve(CACHE[code]); if(LOAD[code])return LOAD[code];
 return LOAD[code]=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=BASE+code+'.js';s.onload=()=>{const data=window.ODYSSEY_I18N_DATA||{};CACHE[code]=data;delete window.ODYSSEY_I18N_DATA;delete LOAD[code];resolve(data)};s.onerror=()=>{delete LOAD[code];reject(new Error('Unable to load language '+code))};document.head.appendChild(s)})}
function getDict(){return CACHE[lang()]||CACHE.en||{}}
function t(key,vars){let v=getDict()[key];if(v==null||v==='')v=(CACHE.en||{})[key];if(v==null||v==='')return null;v=String(v);if(vars)Object.keys(vars).forEach(k=>v=v.replace(new RegExp('\\{'+k+'\\}','g'),String(vars[k])));return v}
function setText(el,key){const v=t(key);if(v!==null)el.textContent=v}
function apply(){const code=lang(),data=getDict(),dir=data.dir||META[code][2];document.documentElement.lang=code;document.documentElement.dir=dir;if(document.body)document.body.dir=dir;
document.querySelectorAll('[data-i18n]').forEach(el=>setText(el,el.dataset.i18n));document.querySelectorAll('[data-i18n-html]').forEach(el=>{const v=t(el.dataset.i18nHtml);if(v!==null)el.innerHTML=v});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const v=t(el.dataset.i18nPlaceholder);if(v!==null)el.placeholder=v});document.querySelectorAll('[data-i18n-title]').forEach(el=>{const v=t(el.dataset.i18nTitle);if(v!==null)el.title=v});document.querySelectorAll('[data-i18n-aria-label]').forEach(el=>{const v=t(el.dataset.i18nAriaLabel);if(v!==null)el.setAttribute('aria-label',v)});document.querySelectorAll('[data-i18n-template]').forEach(el=>{const v=t(el.dataset.i18nTemplate,{count:el.dataset.i18nCount||el.dataset.count||''});if(v!==null)el.textContent=v});
document.querySelectorAll('.i18n-current').forEach(b=>{const m=META[code];b.innerHTML=m[1]+' <span>'+m[0]+'</span> <span aria-hidden="true">▾</span>'});document.querySelectorAll('.i18n-option').forEach(o=>o.classList.toggle('active',o.dataset.lang===code));document.dispatchEvent(new CustomEvent('odyssey:languageChanged',{detail:{lang:code,dir}}))}
async function setLang(code){if(!META[code])code='en';try{await load(code);if(code!=='en')await load('en');localStorage.setItem(KEY,code);apply();}catch(e){console.warn('Odyssey i18n:',e)}}
function switcher(){return '<div class="i18n-switcher"><button class="i18n-current" type="button" aria-haspopup="listbox" data-i18n-aria-label="lang_switcher_aria"><span>🌐</span></button><div class="i18n-dropdown" role="listbox">'+Object.keys(META).map(c=>'<div class="i18n-option" data-lang="'+c+'" role="option">'+META[c][1]+' <span>'+META[c][0]+'</span></div>').join('')+'</div></div>'}
function mount(){document.querySelectorAll('[data-i18n-switcher]').forEach(h=>{if(!h.querySelector('.i18n-switcher'))h.innerHTML=switcher()});document.addEventListener('click',e=>{const b=e.target.closest('.i18n-current');if(b){e.preventDefault();const sw=b.closest('.i18n-switcher');document.querySelectorAll('.i18n-switcher.open').forEach(x=>x!==sw&&x.classList.remove('open'));sw.classList.toggle('open');return}const o=e.target.closest('.i18n-option');if(o){setLang(o.dataset.lang);document.querySelectorAll('.i18n-switcher.open').forEach(x=>x.classList.remove('open'));return}if(!e.target.closest('.i18n-switcher'))document.querySelectorAll('.i18n-switcher.open').forEach(x=>x.classList.remove('open'))});}
const style=document.createElement('style');style.textContent='.i18n-current{display:flex;gap:7px;align-items:center;justify-content:center;border:1px solid rgba(255,255,255,.52);background:linear-gradient(135deg,#0f766e,#2563eb 52%,#e43f8f);color:#fff;border-radius:999px;padding:9px 13px;font-weight:800;font-size:13px;box-shadow:0 10px 28px rgba(37,99,235,.22);cursor:pointer;min-width:132px;white-space:nowrap}.i18n-dropdown{position:absolute;right:0;top:calc(100% + 8px);display:none;min-width:220px;max-height:min(420px,70vh);overflow:auto;background:#fff;border:1px solid rgba(37,99,235,.18);border-radius:16px;box-shadow:0 18px 60px rgba(0,0,0,.18);padding:7px;z-index:2147483647}.i18n-switcher.open .i18n-dropdown{display:block}.i18n-option{padding:9px 11px;border-radius:11px;cursor:pointer;font-weight:700;font-size:13px;white-space:nowrap;color:#24143f}.i18n-option:hover,.i18n-option.active{background:rgba(15,118,110,.10)}.i18n-switcher{position:relative;display:inline-block;z-index:2147483647}';document.head.appendChild(style);
window.OdysseyI18n={LANGS:Object.keys(META).map(c=>({code:c,label:META[c][0],flag:META[c][1],dir:META[c][2]})),t,setLang,getLang:lang,applyTranslations:apply,ensureLangLoaded:load};
(async()=>{try{await load(lang());if(lang()!=='en')await load('en')}catch(e){console.warn('Odyssey i18n initial load failed',e)}mount();apply()})();
})();